---
title: Proxy Network (Velocity / BungeeCord)
description: Connect multiple Minecraft servers behind a proxy using Velocity or BungeeCord.
sidebar:
  order: 2
---

The **Proxy Network** tab helps you set up a proxy server that links multiple Minecraft backends under a single public address. This is the standard architecture for networks with multiple game modes.

## Use Cases

- **Hub + game servers** — players log into a hub and switch to survival, creative, or minigame servers
- **Load balancing** — distribute players across identical backend instances
- **Single address** — all servers share one public IP/port

## Supported Proxy Software

| Software       | Recommendation                                    |
| -------------- | ------------------------------------------------- |
| **Velocity**   | Recommended — modern, maintained, better security |
| **Waterfall**  | BungeeCord fork with more stability               |
| **BungeeCord** | Legacy, still widely supported                    |

## Setup Wizard

1. Navigate to the **Proxy Network** tab.
2. Click **"See Detailed Setup Guide"**.
3. Follow the wizard:
   - **Select proxy software** — Velocity, Waterfall, or BungeeCord
   - **Select backend servers** — choose existing MC-Vector servers to link
   - **Configure proxy port** — default 25577 (must be different from backend ports)
   - **Set forwarding mode** — for Velocity: `modern` (recommended), `legacy`, or `none`

MC-Vector generates the proxy configuration file (`velocity.toml` or `config.yml`) automatically.

## Example: Velocity Configuration

```toml
bind = "0.0.0.0:25577"
motd = "&3My Network"
online-mode = true
force-key-authentication = true
player-info-forwarding-mode = "modern"

[servers]
  hub = "localhost:25565"
  survival = "localhost:25566"
  creative = "localhost:25567"

[forced-hosts]
```

## Backend Server Requirements

For **Velocity modern forwarding** to work, each Paper backend server needs:

1. In `velocity.toml`: `player-info-forwarding-mode = "modern"`
2. In each Paper server's `config/paper-global.yml`:
   ```yaml
   proxies:
     velocity:
       enabled: true
       online-mode: true
       secret: <your-forwarding-secret>
   ```
3. Set `online-mode=false` in `server.properties` on each backend (Velocity handles auth).

:::tip
The forwarding secret is generated by Velocity and must match on all backend servers. MC-Vector copies it into the generated config for you.
:::

## Starting the Network

1. Start the backend servers first.
2. Start the proxy server last.
3. Players connect to the proxy's address (`your-ip:25577`), not the backends directly.

## Player Forwarding Modes

| Mode       | Use when                                                   |
| ---------- | ---------------------------------------------------------- |
| **modern** | All backends are Paper 1.13+ with Velocity support enabled |
| **legacy** | Older BungeeCord-compatible backends                       |
| **none**   | No forwarding needed (all servers in offline mode)         |
